package com.example.composemovieapp.presentation.ui.core.colors

import androidx.compose.ui.graphics.Color

// Progress Colors
val YellowTrackBold = Color(0xFF423d0f)
val YellowBold = Color(0xFFd2d531)
val GreenTrack = Color(0xFF204529)
val GreenBold = Color(0xFF21d07a)
val RedTrack = Color(0xFF571435)
val RedBold = Color(0xFFdb2360)
val DarkBlue = Color(0xFF131E3A)

/** Light theme (overlay) colors **/
val ColorPrimary = Color(0xFF3772FF)
val ColorOnPrimary = Color(0xFFFFFFFF)
val ColorOverlay = Color(0xFF48464C)
val ColorPrimaryContainer = Color(0xFFD2E4FF)
val ColorOnPrimaryContainer = Color(0xFF001C37)
val ColorPrimaryFixed = Color(0xFFEADDFF)
val ColorOnPrimaryFixed = Color(0xFF21005D)
val ColorPrimaryFixedDim = Color(0xFF4F378B)
val ColorOnPrimaryFixedVariant = Color(0xFF4F378B)
val ColorSecondary = Color(0xFF2E5DA8)
val ColorOnSecondary = Color(0xFFFFFFFF)
val ColorSecondaryContainer = Color(0xFFD7E2FF)
val ColorOnSecondaryContainer = Color(0xFF001A40)
val ColorSecondaryFixed = Color(0xFFE8DEF8)
val ColorOnSecondaryFixed = Color(0xFF1D192B)
val ColorSecondaryFixedDim = Color(0xFFCCC2DC)
val ColorOnSecondaryFixedVariant = Color(0xFF4A4458)
val ColorTertiary = Color(0xFF0B61A4)
val ColorOnTertiary = Color(0xFFFFFFFF)
val ColorTertiaryContainer = Color(0xFFD2E4FF)
val ColorOnTertiaryContainer = Color(0xFF001C37)
val ColorError = Color(0xFFB3261E)
val ColorOnError = Color(0xFFFFFFFF)
val ColorErrorContainer = Color(0xFFF9DEDC)
val ColorOnErrorContainer = Color(0xFF410E0B)
val ColorOutline = Color(0xFF79747E)
val ColorOnBackground = Color(0xFF191C20)
val ColorSurface = Color(0xFFF8F9FF)
val ColorOnSurface = Color(0xFF191C20)
val ColorSurfaceVariant = Color(0xFFDFE2EB)
val ColorOnSurfaceVariant = Color(0xFF43474E)
val ColorSurfaceInverse = Color(0xFF322F35)
val ColorOnSurfaceInverse = Color(0xFFF5EFF7)
val ColorPrimaryInverse = Color(0xFFA0C9FF)
val ColorOutlineVariant = Color(0xFFCAC4D0)
val ColorSurfaceContainerHighest = Color(0xFFE6E0E9)
val ColorSurfaceContainerHigh = Color(0xFFDEE9F5)
val ColorSurfaceContainer = Color(0xFFF3EDF7)
val ColorSurfaceContainerLow = Color(0xFFECF1FA)
val ColorSurfaceContainerLowest = Color(0xFFFFFFFF)
val ColorSurfaceBright = Color(0xFFF8F9FF)
val ColorSurfaceDim = Color(0xFFD8DCE1)
val ColorInverseSurface = Color(0xFF322F35)
val ColorInverseOnSurface = Color(0xFFF5EFF7)

/** Dark theme (overlay) colors **/
val ColorPrimaryDark = Color(0xFFA0C9FF)
val ColorOnPrimaryDark = Color(0xFF00325A)
val ColorOverlayDark = Color(0xFFAEA9B1)
val ColorPrimaryContainerDark = Color(0xFF00497F)
val ColorOnPrimaryContainerDark = Color(0xFFD2E4FF)
val ColorPrimaryFixedDark = Color(0xFFEADDFF)
val ColorOnPrimaryFixedDark = Color(0xFF21005D)
val ColorPrimaryFixedDimDark = Color(0xFFD0BCFF)
val ColorOnPrimaryFixedVariantDark = Color(0xFF4F378B)
val ColorSecondaryDark = Color(0xFFACC7FF)
val ColorOnSecondaryDark = Color(0xFF002F67)
val ColorSecondaryContainerDark = Color(0xFF08458E)
val ColorOnSecondaryContainerDark = Color(0xFFD7E2FF)
val ColorSecondaryFixedDark = Color(0xFFE8DEF8)
val ColorOnSecondaryFixedDark = Color(0xFF1D192B)
val ColorSecondaryFixedDimDark = Color(0xFFCCC2DC)
val ColorOnSecondaryFixedVariantDark = Color(0xFF4A4458)
val ColorTertiaryDark = Color(0xFFEFB8C8)
val ColorOnTertiaryDark = Color(0xFF492532)
val ColorTertiaryContainerDark = Color(0xFF633B48)
val ColorOnTertiaryContainerDark = Color(0xFFFFD8E4)
val ColorErrorDark = Color(0xFFF2B8B5)
val ColorOnErrorDark = Color(0xFF601410)
val ColorErrorContainerDark = Color(0xFF8C1D18)
val ColorOnErrorContainerDark = Color(0xFFF9DEDC)
val ColorOutlineDark = Color(0xFF938F99)
val ColorOnBackgroundDark = Color(0xFFDBDDE3)
val ColorSurfaceDark = Color(0xFF191C20)
val ColorOnSurfaceDark = Color(0xFFDBDDE3)
val ColorSurfaceVariantDark = Color(0xFF43474E)
val ColorOnSurfaceVariantDark = Color(0xFFC3C6CF)
val ColorSurfaceInverseDark = Color(0xFFE6E0E9)
val ColorOnSurfaceInverseDark = Color(0xFF322F35)
val ColorPrimaryInverseDark = Color(0xFF0B61A4)
val ColorOutlineVariantDark = Color(0xFF49454F)
val ColorSurfaceContainerHighestDark = Color(0xFF36404C)
val colorSurfaceContainerHighDark = Color(0xFF282F38)
val colorSurfaceContainerDark = Color(0xFF242A31)
val colorSurfaceContainerLowDark = Color(0xFF20252B)
val colorSurfaceContainerLowestDark = Color(0xFF0F0D13)
val colorSurfaceBrightDark = Color(0xFF282F38)
val colorSurfaceDimDark = Color(0xFF20252B)
val ColorInverseSurfaceDark = Color(0xFF322F35)
val ColorInverseOnSurfaceDark = Color(0xFFE6E0E9)

val lightPalette = MovieColors(
    colorPrimary = ColorPrimary,
    colorOnPrimary = ColorOnPrimary,
    colorOverlay = ColorOverlay,
    colorPrimaryContainer = ColorPrimaryContainer,
    colorOnPrimaryContainer = ColorOnPrimaryContainer,
    colorPrimaryFixed = ColorPrimaryFixed,
    colorOnPrimaryFixed = ColorOnPrimaryFixed,
    colorPrimaryFixedDim = ColorPrimaryFixedDim,
    colorOnPrimaryFixedVariant = ColorOnPrimaryFixedVariant,
    colorSecondary = ColorSecondary,
    colorOnSecondary = ColorOnSecondary,
    colorSecondaryContainer = ColorSecondaryContainer,
    colorOnSecondaryContainer = ColorOnSecondaryContainer,
    colorSecondaryFixed = ColorSecondaryFixed,
    colorOnSecondaryFixed = ColorOnSecondaryFixed,
    colorSecondaryFixedDim = ColorSecondaryFixedDim,
    colorOnSecondaryFixedVariant = ColorOnSecondaryFixedVariant,
    colorTertiary = ColorTertiary,
    colorOnTertiary = ColorOnTertiary,
    colorTertiaryContainer = ColorTertiaryContainer,
    colorOnTertiaryContainer = ColorOnTertiaryContainer,
    colorError = ColorError,
    colorOnError = ColorOnError,
    colorErrorContainer = ColorErrorContainer,
    colorOnErrorContainer = ColorOnErrorContainer,
    colorOutline = ColorOutline,
    colorOnBackground = ColorOnBackground,
    colorSurface = ColorSurface,
    colorOnSurface = ColorOnSurface,
    colorSurfaceVariant = ColorSurfaceVariant,
    colorOnSurfaceVariant = ColorOnSurfaceVariant,
    colorSurfaceInverse = ColorSurfaceInverse,
    colorOnSurfaceInverse = ColorOnSurfaceInverse,
    colorInversePrimary = ColorPrimaryInverse,
    colorOutlineVariant = ColorOutlineVariant,
    colorSurfaceContainerHighest = ColorSurfaceContainerHighest,
    colorSurfaceContainerHigh = ColorSurfaceContainerHigh,
    colorSurfaceContainer = ColorSurfaceContainer,
    colorSurfaceContainerLow = ColorSurfaceContainerLow,
    colorSurfaceContainerLowest = ColorSurfaceContainerLowest,
    colorSurfaceBright = ColorSurfaceBright,
    colorSurfaceDim = ColorSurfaceDim,
    colorInverseSurface = ColorInverseSurface,
    colorInverseOnSurface = ColorInverseOnSurface,
    isDark = false,
)

val darkPalette = MovieColors(
    colorPrimary = ColorPrimaryDark,
    colorOnPrimary = ColorOnPrimaryDark,
    colorOverlay = ColorOverlayDark,
    colorPrimaryContainer = ColorPrimaryContainerDark,
    colorOnPrimaryContainer = ColorOnPrimaryContainerDark,
    colorPrimaryFixed = ColorPrimaryFixedDark,
    colorOnPrimaryFixed = ColorOnPrimaryFixedDark,
    colorPrimaryFixedDim = ColorPrimaryFixedDimDark,
    colorOnPrimaryFixedVariant = ColorOnPrimaryFixedVariantDark,
    colorSecondary = ColorSecondaryDark,
    colorOnSecondary = ColorOnSecondaryDark,
    colorSecondaryContainer = ColorSecondaryContainerDark,
    colorOnSecondaryContainer = ColorOnSecondaryContainerDark,
    colorSecondaryFixed = ColorSecondaryFixedDark,
    colorOnSecondaryFixed = ColorOnSecondaryFixedDark,
    colorSecondaryFixedDim = ColorSecondaryFixedDimDark,
    colorOnSecondaryFixedVariant = ColorOnSecondaryFixedVariantDark,
    colorTertiary = ColorTertiaryDark,
    colorOnTertiary = ColorOnTertiaryDark,
    colorTertiaryContainer = ColorTertiaryContainerDark,
    colorOnTertiaryContainer = ColorOnTertiaryContainerDark,
    colorError = ColorErrorDark,
    colorOnError = ColorOnErrorDark,
    colorErrorContainer = ColorErrorContainerDark,
    colorOnErrorContainer = ColorOnErrorContainerDark,
    colorOutline = ColorOutlineDark,
    colorOnBackground = ColorOnBackgroundDark,
    colorSurface = ColorSurfaceDark,
    colorOnSurface = ColorOnSurfaceDark,
    colorSurfaceVariant = ColorSurfaceVariantDark,
    colorOnSurfaceVariant = ColorOnSurfaceVariantDark,
    colorSurfaceInverse = ColorSurfaceInverseDark,
    colorOnSurfaceInverse = ColorOnSurfaceInverseDark,
    colorInversePrimary = ColorPrimaryInverseDark,
    colorOutlineVariant = ColorOutlineVariantDark,
    colorSurfaceContainerHighest = ColorSurfaceContainerHighestDark,
    colorSurfaceContainerHigh = colorSurfaceContainerHighDark,
    colorSurfaceContainer = colorSurfaceContainerDark,
    colorSurfaceContainerLow = colorSurfaceContainerLowDark,
    colorSurfaceContainerLowest = colorSurfaceContainerLowestDark,
    colorSurfaceBright = colorSurfaceBrightDark,
    colorSurfaceDim = colorSurfaceDimDark,
    colorInverseSurface = ColorInverseSurfaceDark,
    colorInverseOnSurface = ColorInverseOnSurfaceDark,
    isDark = true,
)